#!/bin/bash

docker run -it -p 139:139 -p 445:445 \
--name 1c-samba \
--rm \
-v /mnt/SDA700:/mnt/SDA700 \
-v /mnt/SDA300:/mnt/SDA300 \
-d dperson/samba \
-u "user;user" \
-u "admin;admin" \
-s "public;/mnt/SDA700;yes;no;no;user" \
-s "backup;/mnt/SDA300;yes;no;no;user" 
